### ISSUE TITLE
wn2vec.zip is no longer available

### ISSUE THREAD

**Issue by M49ICKPIxi3** [nlx-group/WordNetEmbeddings#4]
The link in the README.md file [http://lxcenter.di.fc.ul.pt/wn2vec.zip](http://lxcenter.di.fc.ul.pt/wn2vec.zip) no longer works. Do you or anyone else have a copy of this? 

I'd really appreciate it! Thank you

**Comment by nlx-group** [comment]
The problem seems to have been resolved
